export const data = [
  {title:"123A", content:"Vivamus sed metus blandit, sodales urna sit amet, rutrum ante. Etiam elementum libero at sem sollicitudin, non maximus erat malesuada. Praesent fringilla pretium fringilla. Mauris mattis efficitur diam, quis eleifend mi finibus ac. Vestibulum non nunc et quam sagittis maximus. Vestibulum quis nisi et velit bibendum efficitur ac eget risus. Nam egestas tellus id massa semper dapibus. Sed non ipsum sit amet arcu eleifend scelerisque vulputate eu nulla. Ut lacinia lacus id convallis fermentum."},
  {title:"123B", content:"Vestibulum nec laoreet nisl, a lobortis sapien. Aenean vel leo dictum, porttitor nisl vitae, blandit libero. Pellentesque eu ante eleifend erat accumsan finibus. Suspendisse sagittis, nulla ut aliquet porttitor, lorem lacus aliquam dolor, scelerisque imperdiet sem velit et diam. Ut vulputate metus et arcu bibendum lacinia. Aenean luctus molestie felis, nec euismod erat vulputate ut. In feugiat sagittis dolor, quis venenatis eros interdum non. Sed pharetra purus eget lobortis cursus. Sed sodales facilisis turpis, posuere dapibus mi. Nullam at facilisis justo, ac lacinia ligula. Pellentesque a velit ac enim gravida volutpat vitae a quam. Suspendisse consectetur maximus urna, at lacinia justo luctus a. Curabitur eu placerat sem. Nulla blandit laoreet nisi sed gravida. Aenean eget est ac odio consequat auctor volutpat vitae est."},
  {title:"123C", content:"Fusce ullamcorper gravida sem, eu commodo magna tincidunt tempor. Donec vel porttitor nulla, at dapibus justo. Donec in orci non diam interdum elementum et nec diam. Proin tincidunt diam eu dui dignissim, vitae tempor nisi euismod. Nam sit amet maximus arcu. Aliquam leo nibh, viverra sit amet mauris nec, pharetra semper lorem. Etiam rutrum sapien ac neque feugiat, quis elementum mauris commodo. Duis urna magna, blandit in nisi at, bibendum rutrum erat. Cras maximus ut nunc nec egestas. Aenean viverra orci felis, nec dapibus lorem consequat sed. Aenean ac felis quam. Quisque consequat arcu dui, non mollis neque condimentum id. Integer nec blandit purus. Quisque a magna interdum, ullamcorper lacus eu, vestibulum dui. Donec nec auctor sapien, finibus feugiat arcu."},
  {title:"123D", content:"Cras pulvinar posuere ipsum sit amet lobortis. Nam convallis leo id tristique dignissim. Suspendisse id blandit odio. Pellentesque malesuada eros a justo accumsan egestas. Integer scelerisque accumsan metus, id fermentum neque luctus a. Fusce ornare nisi nec aliquet luctus. Phasellus lectus metus, convallis a leo eu, lobortis pretium lacus. Pellentesque sit amet lorem a felis interdum pretium congue ullamcorper quam. Vivamus porttitor, magna eget sodales faucibus, ipsum elit ultricies magna, a finibus ex arcu in massa. Vestibulum sit amet hendrerit nulla. Quisque non purus vel mauris consequat hendrerit."},
];




